env:
  global:
  - CC_TEST_REPORTER_ID=02cd1b70507cc6f516c3440b02d7238db03acc5e3b6d66331ce20381432b9b24
  - FOREMAN=1.17.1
language: ruby
sudo: required
services: 
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - docker build -t foreman/proxmox .
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rake test:foreman_proxmox
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"