language: ruby
rvm:
  - 2.6.6
sudo: required
services: 
  - docker
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
  env:
    global:
    - PGPORT=5432
before_install:
  - psql -c 'create user foreman;' -U postgres
  - psql -c 'create database "foreman-test";' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE "foreman-test" TO foreman;' -U postgres
install:
  - docker build -t foreman/proxmox .
  - docker run foreman/proxmox /bin/sh -c "bundle exec bin/rake db:migrate"
  - docker run foreman/proxmox /bin/sh -c "bundle exec bin/rake db:seed assets:precompile locale:pack webpack:compile"
script:  
  - docker run foreman/proxmox /bin/sh -c "bundle exec bin/rake foreman_fog_proxmox:rubocop test:foreman_fog_proxmox"