language: ruby
rvm:
  - 2.6.6
sudo: required
services: 
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - docker run -e POSTGRES_DB="foreman-test" -e POSTGRES_USER=foreman -e POSTGRES_PASSWORD=foreman -p 127.0.0.1:5432:5432 -d postgres
  - docker build -t foreman/proxmox .
  - docker run foreman/proxmox /bin/sh -c "bundle exec bin/rake db:migrate"
  - docker run foreman/proxmox /bin/sh -c "bundle exec bin/rake db:seed assets:precompile locale:pack webpack:compile"
script:
  - docker run foreman/proxmox /bin/sh -c "bundle exec bin/rake foreman_fog_proxmox:rubocop test:foreman_fog_proxmox"