name: CI test foreman plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_USER=foreman
          POSTGRES_PASSWORD=foreman
          POSTGRES_DB=foreman
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: theforeman/foreman
        ref: develop
        path: foreman
    - uses: actions/checkout@v2
      with:
        repository: theforeman/foreman_fog_proxmox
        path: foreman_fog_proxmox
    - uses: actions/checkout@v2
      with:
        repository: fog/fog-proxmox
        path: fog-proxmox
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' 
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' 
    - name: Setup foreman
      env:
        PGHOST: 127.0.0.1
        PGDB: foreman
        PGPWD: foreman
        PGUSER: foreman
        RAILS_ENV: test
        DISABLE_SPRING: true
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        echo "gem 'foreman_fog_proxmox', :path => 'foreman_fog_proxmox'\n" > foreman/bundler.d/Gemfile.local.rb
        echo "gem 'fog-proxmox', :path => 'fog-proxmox'\n" >> foreman/bundler.d/Gemfile.local.rb
        echo "gem 'simplecov'" >> foreman/bundler.d/Gemfile.local.rb
        cp foreman/config/settings.yaml.test foreman/config/settings.yaml
        echo "test:\n adapter: postgresql \n port: 5432 \n database: foreman \n encoding: utf8 \n pool: 10" > foreman/config/database.yml
        cp foreman/config/model.mappings.example foreman/config/model.mappings
        cp foreman/config/ignored_environments.yml.sample foreman/config/ignored_environments.yml
        bundle install --jobs 4 --retry 3
        bundle exec foreman/bin/rake db:migrate
        bundle exec foreman/bin/rake db:seed assets:precompile locale:pack webpack:compile
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - name: Run test suite
      run: |
        bundle exec foreman/bin/rake foreman_fog_proxmox:rubocop
        bundle exec foreman/bin/rake test:foreman_fog_proxmox
